### ISSUE TITLE
HTML Basic

### ISSUE THREAD

**Issue by welesonbatista** [welesonbatista/iginite-shop#1]
**Tasks**
- [x] O que é HTML?
- [x] Anatomia de um Elemento HTML
- [x] Atributos: id, class, data-*, style
- [x] Aninhamento de Elementos
- [x] Elementos Vazios
- [x] Estrutura de um Documento HTML
- [x] Estrutura: header, nav, main, aside, section, article e footer
- [x] Cabeçalhos: h1 a h6
- [x] Parágrafos: p, strong, time
- [x] Listas: ul, ul li
- [x] Links:`<a>` e `href`
- [x] Vê bloco de aulas [Elementos Estruturais](https://app.rocketseat.com.br/classroom/iniciando-o-html-e-css-2/group/elementos-estruturais/lesson/anatomia-de-um-documento-html)
- [x] [Fazer exercício](https://github.com/users/welesonbatista/projects/2?pane=issue&itemId=90238770&issue=welesonbatista%7Ciginite-shop%7C2)

**Comment by welesonbatista** [comment]
### HTML Básico: Revisado e Melhorado

### O que é HTML?

HTML é uma **linguagem de marcação** usada para definir a estrutura de uma página. Com HTML, é possível transformar texto em parágrafos, títulos, links, imagens e muito mais.

---
### Anatomia de um Elemento HTML

Um elemento HTML é composto por várias partes:

1. **Tag de Abertura**  
    Indica onde o elemento começa. É composta pelo nome do elemento (ex.: `p`), envolvido por `<` e `>`.  
    Exemplo: `<p>`
    
2. **Tag de Fechamento**  
    Indica onde o elemento termina. É semelhante à tag de abertura, mas inclui uma barra `/` antes do nome do elemento.  
    Exemplo: `</p>`
    
3. **Conteúdo**  
    É o texto ou outro elemento contido dentro do elemento.  
    Exemplo: `Meu gatinho é muito mal-humorado.`
    
4. **Elemento Completo**  
    A combinação das tags de abertura, conteúdo e tag de fechamento forma um elemento completo.  
    Exemplo:

```html
<p>Meu gatinho é muito mal-humorado.</p>
```

---

### Atributos

Atributos fornecem informações adicionais aos elementos. Eles são declarados na tag de abertura e seguem o formato:  
`nome-do-atributo="valor"`

Exemplo:
```html
<p class="editor-note">Texto importante</p>
```

Aqui, o atributo `class` identifica o elemento como pertencente à classe "editor-note".

#### Regras dos Atributos:

- Devem ser separados por espaço após o nome do elemento.
- Os valores devem estar entre aspas (`"`), mesmo quando não contêm espaços.

#### id
- Define um **identificador exclusivo** para um elemento HTML, que deve ser único em todo o documento.
- É usado para **selecionar** ou **acessar** o elemento por CSS e JavaScript.

##### Exemplo:

```html
<footer id="contato">
  <p>Contato: contato@exemplo.com</p>
</footer>

<!-- CSS -->
<style>
  #contato {
    background-color: #f4f4f4;
    padding: 10px;
    text-align: center;
  }
</style>
```

#### class
- Permite atribuir uma ou mais **classes** a um elemento.
- As classes são separadas por **espaços** e podem ser usadas para aplicar estilos em grupo ou acessar elementos no JavaScript.

```html
<div class="card destaque">
  <h2>Produto 1</h2>
  <p>Descrição do produto.</p>
</div>

<!-- CSS -->
<style>
  .card {
    border: 1px solid #ccc;
    padding: 15px;
    margin: 10px;
  }

  .destaque {
    background-color: #ffe4b5;
  }
</style>
```

#### data-*
- É uma categoria de atributos personalizados que permite armazenar **dados adicionais** diretamente no HTML.
- Esses dados podem ser acessados e manipulados pelo **JavaScript**.
- A convenção é usar o prefixo `data-`, seguido pelo nome do atributo.

```html
<div data-produto-id="1234" data-preco="29.90">
  <h3>Produto 1</h3>
</div>

<!-- JavaScript -->
<script>
  const produto = document.querySelector('[data-produto-id]');
  console.log(produto.dataset.produtoId); // Saída: 1234
  console.log(produto.dataset.preco); // Saída: 29.90
</script>
```

#### style
- Permite adicionar **estilos inline**, ou seja, diretamente na tag do elemento.
- Geralmente, o uso de estilos inline não é recomendado, pois dificulta a manutenção do código. É preferível utilizar arquivos CSS externos ou internos.

```html
<p style="color: red; font-weight: bold;">
  Este texto está estilizado diretamente na tag.
</p>
```


---

### Aninhamento de Elementos

Elementos HTML podem ser **aninhados**, ou seja, colocados dentro de outros elementos. Isso permite criar estruturas hierárquicas.

Exemplo correto:

```html
<p>Meu gatinho é <strong>muito</strong> mal-humorado.</p>
```

---

### Elementos Vazios

Alguns elementos não possuem conteúdo interno, como `<img>`. Esses elementos são chamados de **vazios** e não têm uma tag de fechamento.

Exemplo:

```html
<img src="https://github.com/welesonbatista.png" alt="Foto de um gato mal-humorado" />
```

Aqui, o atributo `src` define o caminho da imagem, enquanto `alt` fornece um texto descritivo para casos em que a imagem não é exibida.

---

### Estrutura de um Documento HTML

Um arquivo HTML completo segue esta estrutura básica:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Minha Página de Teste</title>
  </head>
  <body>
    <h1>Bem-vindo!</h1>
    <p>Este é um exemplo básico de HTML.</p>
  </body>
</html>
```

#### Explicação:

1. **`<!DOCTYPE html>`**: Declaração obrigatória que informa ao navegador que o documento usa HTML5.
2. **`<html>`**: Elemento raiz que envolve todo o conteúdo.
3. **`<head>`**: Contém metadados (informações não visíveis para o usuário).
4. **`<body>`**: Abriga o conteúdo visível, como texto, imagens, vídeos, etc.

---
### Estrutura

#### **Header**
- Representa o **cabeçalho** de um documento ou **seção**.
- Pode conter elementos como títulos (`h1` a `h6`), imagens, parágrafos e listas de navegação.

```html
<header>
    <h1>Título da página</h1>
    <h2>Subtítulo</h2>
</header>
```

#### **Nav**
- Agrupa links de **navegação** do site.
- Usa elementos como `<ul>`, `<li>`, e `<a>` para construir a lista.

```html
<nav>
    <ul>
        <li><a href="#pagina1">Página 1</a></li>
        <li><a href="#pagina2">Página 2</a></li>
    </ul>
</nav>
```
#### **Main**
- Define o **conteúdo principal** da página. Deve ser único em cada documento HTML.

```html
<main>
    <h2>Título Principal</h2>
    <p>Conteúdo principal...</p>
</main>
```

#### **Aside**
- Usado para conteúdo **secundário ou de apoio**, como menus laterais ou widgets.

```html
<aside>
    <nav>
        <ul>
            <li>Link 1</li>
            <li>Link 2</li>
        </ul>
    </nav>
</aside>
```

#### **Section**
- Representa uma **seção** do documento, geralmente com um título.
- Ideal para dividir o conteúdo em **tópicos específicos**.

```html
<section>
    <h3>Seção 1</h3>
    <p>Lorem ipsum dolor sit amet...</p>
</section>
```

#### **Article**
- Indica conteúdo **independente**, como artigos ou postagens.
- É usado quando o conteúdo pode ser compreendido sozinho.

```html
<article>
    <h3>Artigo 1</h3>
    <p>Texto do artigo...</p>
</article>
```


#### **Footer**
- Representa o **rodapé**, usado para informações de autoria, datas ou links adicionais.

```html
<footer>
    <p>Autor: Weleson Batista</p>
    <p>Publicado em 25/03/2017</p>
</footer>
```




---
### Marcando o Texto

#### **Cabeçalhos**

Os cabeçalhos estruturam títulos e subtítulos. Existem seis níveis: `<h1>` (mais importante) a `<h6>` (menos importante).

Exemplo:

```html
<h1>Título Principal</h1>
<h2>Subtítulo</h2>
<h3>Subtítulo Menor</h3>
```

#### **Parágrafos**

Usados para criar blocos de texto.

```html
<p>Este é um parágrafo simples.</p>
```

**`<strong>`**
- Dá **ênfase mais forte** ao conteúdo.

```html
<p><strong>Importante:</strong> Leia as instruções antes de começar.</p>
```

**`<time>`**
- Representa uma **data ou hora**, com o atributo `datetime` para padronização.

```html
<time datetime="2024-12-09">9 de dezembro de 2024</time>
```


---

### Listas

HTML suporta dois tipos de listas:

- **Não Ordenadas (`<ul>`)**: Usadas para itens sem ordem específica.
    ```html
    <ul>
      <li>Item 1</li>
      <li>Item 2</li>
    </ul>
    ```

- **Ordenadas (`<ol>`)**: Usadas para itens em sequência.
    ```html
    <ol>
      <li>Primeiro</li>
      <li>Segundo</li>
    </ol>
    ```

---

### Links

Links são criados com o elemento `<a>` e o atributo `href`, que especifica o endereço do link.

```html
<a href="https://github.com/welesonbatista">Meu GitHub</a>
```

---

### Acessibilidade com Texto Alternativo

Ao usar imagens, o atributo `alt` deve descrever o conteúdo para pessoas com deficiência visual ou em caso de erro no carregamento da imagem.

Exemplo de descrição adequada:

```html
<img src="logo.png" alt="Logo da empresa: uma raposa laranja envolvendo um globo azul." />
```

---

# [Mais info](https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/HTML_basics)


## Resumo

| **Conceito**                 | **Descrição**                                                          | **Exemplo**                                                                                |
| ---------------------------- | ---------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| **HTML**                     | Linguagem de marcação usada para estruturar o conteúdo de páginas web. | `<p>Meu gatinho é muito mal-humorado.</p>`                                                 |
| **Tag de Abertura**          | Define onde o elemento começa.                                         | `<p>`                                                                                      |
| **Tag de Fechamento**        | Define onde o elemento termina.                                        | `</p>`                                                                                     |
| **Elemento Completo**        | Combinação da tag de abertura, conteúdo e tag de fechamento.           | `<p>Meu gatinho é muito mal-humorado.</p>`                                                 |

| **Conceito**                 | **Descrição**                                                    | **Exemplo**                                                                                |
| ---------------------------- | ---------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| **Atributos**                | Adicionam informações extras aos elementos HTML.                 | `<p class="editor-note">Texto importante</p>`                                              |
| **`id`**                     | Identifica um elemento de forma exclusiva no documento.          | `<footer id="contato"></footer>`                                                           |
| **`class`**                  | Agrupa elementos para estilização ou scripts.                    | `<div class="card destaque"></div>`                                                        |
| **`data-*`**                 | Armazena dados personalizados para uso em JavaScript.            | `<div data-produto-id="1234" data-preco="29.90"></div>`                                    |
| **`style`**                  | Define estilos inline diretamente no elemento.                   | `<p style="color: red;">Texto vermelho</p>`                                                |

| **Conceito**                 | **Descrição**                                                    | **Exemplo**                                                                                |
| ---------------------------- | ---------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| **Header**                   | Define o cabeçalho do documento ou seção.                        | `<header><h1>Título da página</h1></header>`                                               |
| **Nav**                      | Agrupa links de navegação do site.                               | `<nav><ul><li><a href="#home">Home</a></li></ul></nav>`                                    |
| **Main**                     | Define o conteúdo principal da página.                           | `<main><h2>Conteúdo Principal</h2></main>`                                                 |
| **Aside**                    | Usado para conteúdo auxiliar ou de apoio.                        | `<aside><p>Informação lateral</p></aside>`                                                 |
| **Section**                  | Representa uma seção de conteúdo.                                | `<section><h3>Seção 1</h3></section>`                                                      |
| **Article**                  | Representa um conteúdo independente, como um artigo ou postagem. | `<article><h3>Artigo 1</h3></article>`                                                     |
| **Footer**                   | Representa o rodapé do documento ou seção.                       | `<footer><p>Autor: Weleson Batista</p></footer>`                                           |

| **Conceito**   | **Descrição**                              | **Exemplo**                                                |
| -------------- | ------------------------------------------ | ---------------------------------------------------------- |
| **Cabeçalhos** | Estruturam títulos e subtítulos da página. | `<h1>Título Principal</h1>`                                |
| **Parágrafos** | Representam blocos de texto.               | `<p>Texto de exemplo.</p>`                                 |
| **`<strong>`** | Dá ênfase forte ao texto.                  | `<p><strong>Importante:</strong> Leia o manual.</p>`       |
| **`<time>`**   | Representa uma data ou hora.               | `<time datetime="2024-12-09">9 de dezembro de 2024</time>` |

| **Conceito**                 | **Descrição**                                      | **Exemplo**                                                                                |
| ---------------------------- | -------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| **Listas Não Ordenadas**     | Exibem itens sem ordem específica.                 | `<ul><li>Item 1</li><li>Item 2</li></ul>`                                                  |
| **Listas Ordenadas**         | Exibem itens em ordem sequencial.                  | `<ol><li>Primeiro</li><li>Segundo</li></ol>`                                               |
| **Links**                    | Transformam texto ou elementos em links clicáveis. | `<a href="https://github.com/welesonbatista">Meu GitHub</a>`                               |
| **Imagens (`<img>`)**        | Insere imagens no documento HTML.                  | `<img src="logo.png" alt="Logo da empresa: uma raposa laranja envolvendo um globo azul.">` |
